#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2019, PhysK
# All rights reserved.

# shellcheck disable=SC2086
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}
DIR_CACHE_TIME=${DIR_CACHE_TIME:-2m}
VFS_READ_CHUNK_SIZE=${VFS_READ_CHUNK_SIZE:-96M}
VFS_CACHE_MAX_AGE=${VFS_CACHE_MAX_AGE:-675h}
VFS_READ_CHUNK_SIZE_LIMIT=${VFS_READ_CHUNK_SIZE_LIMIT:-1G}
VFS_CACHE_MODE=${VFS_CACHE_MODE:-minimal}
VFS_CACHE_MAX_SIZE=${VFS_CACHE_MAX_SIZE:-100G}
BUFFER_SIZE=${BUFFER_SIZE:-48M}
RC_ENABLED=${RC_ENABLED:-false}
RC_ADDR=${RC_ADDR:-0.0.0.0:5572}
RC_USER=${RC_USER:-user}
RC_PASS=${RC_PASS:-xxx}
POLL_INTERVAL=${POLL_INTERVAL:-5m}


if [ "${RC_ENABLED}" == "true" ]; then
    RC_CMD="--rc --rc-addr ${RC_ADDR} --rc-user ${RC_USER} --rc-pass ${RC_PASS}"
fi

umask 022

mount_command="/usr/bin/rclone \
--allow-non-empty \
--allow-other \
mount tdrive:Media /mnt/tdrive1 \
--uid=${PUID} \
--gid=${PGID} \
--size-only \
--cache-dir /tmp/rclone_cache/ \
--dir-cache-time ${DIR_CACHE_TIME} \
--vfs-read-chunk-size ${VFS_READ_CHUNK_SIZE} \
--vfs-cache-max-age ${VFS_CACHE_MAX_AGE} \
--vfs-read-chunk-size-limit ${VFS_READ_CHUNK_SIZE_LIMIT} \
--vfs-cache-mode ${VFS_CACHE_MODE} \
--vfs-cache-max-size ${VFS_CACHE_MAX_SIZE} \
--poll-interval ${POLL_INTERVAL} \
--buffer-size ${BUFFER_SIZE} \
--umask 002 \
${RC_CMD}
--log-level DEBUG \
--config /config/rclone-docker.conf \
--log-file /tmp/mount-tdrive1.log"


echo "-> Mounting tdrive1 <-"
exec s6-setuidgid abc $mount_command
