#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2019, PhysK
# All rights reserved.

# shellcheck disable=SC2086

umask 022
nginx_command="nginx"
echo "-> Starting nginx <-"
exec s6-setuidgid abc $nginx_command