#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2019, PhysK
# All rights reserved.
DISABLE_UNIONFS_CHOWN=${DISABLE_UNIONFS_CHOWN:-false}

echo "-> Making sure we have the correct Directorys <-"
mkdir -p /mnt/tdrive1
mkdir -p /mnt/tdrive2
mkdir -p /mnt/gdrive
mkdir -p /move/Media

echo "-> Setting Permissions <-"

chown -hR abc:abc \
	/config
chown -hR abc:abc \
    /mnt
chown -hR abc:abc \
    /move
if [ "${DISABLE_UNIONFS_CHOWN}" == "false" ]; then
    chown -hR abc:abc \
        /unionfs
else
    echo "-> Unionfs Chown disabled <-"
fi

chown -R abc:abc \
    /run
chown -R abc:abc \
    /var/lib/nginx
chown -R abc:abc \
    /var/tmp/nginx
chown -R abc:abc \
    /var/log/nginx
chown -R abc:abc \
    /var/www
chmod +x \
    /usr/local/bin/check_mounts.sh
chown abc:abc \
    /usr/local/bin/check_mounts.sh
