#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2019, PhysK
# All rights reserved.

DISABLE_TDRIVE2=${DISABLE_TDRIVE2:-false}

if [ "${DISABLE_TDRIVE2}" == "true" ] || ! grep -q tdrive2 /config/rclone-docker.conf; then
    touch /etc/services.d/mount-tdrive2/down
    echo "-> Disabled tdrive2 Mount <-"
else
    echo "${UFSTMP}:/mnt/tdrive2=NC" > /tmp/ufs.path
fi
