#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2019, PhysK
# All rights reserved.

DISABLE_WEB=${DISABLE_WEB:-false}

if [ "${DISABLE_WEB}" == "true" ]; then
    touch /etc/services.d/php-fpm/down
    touch /etc/services.d/nginx/down
    echo "-> Disabled Web Tracker <-"
fi